server:
  port: 8855
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data;

  jpa:
    hibernate:
      ddl-auto: create # create, update, validate, none in production update